In [65]:
import os 
import math
import random
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from scipy.stats import kendalltau
from scipy.stats import rankdata
from sklearn.model_selection import train_test_split
from numpy import count_nonzero

dir_ = '../data/'
group_dir_ = '../data/groups/low'

In [66]:
file_name = 'normalized_to_rating_filter_track_5_user_100.csv'
svd = pd.read_pickle(os.path.join(dir_, 'prediction_svd_top_N_' + file_name[:-3] + 'pkl'))
test = pd.read_pickle(os.path.join(dir_, 'test_' + file_name[:-3] + 'pkl'))
test.sort_values(by=['uid','tid'])

file_name = 'normalized_popularity_filter_track_5_user_100.csv'
pop_count = pd.read_pickle(os.path.join(dir_, 'prediction_popularity_count_top_N_' + file_name[:-3] + 'pkl'))
pop_rating = pd.read_pickle(os.path.join(dir_, 'prediction_popularity_rating_top_N_' + file_name[:-3] + 'pkl'))

num_user = len(svd['uid'].unique())
num_user

220

In [67]:
groups_n_train = []
groups_n_test = []
group_sizes = ['2', '3', '4', '5']
for i in range(len(group_sizes)):
    groups = np.loadtxt(os.path.join(group_dir_, 'group_' + group_sizes[i] + '.csv'), delimiter=',')
    num_groups = len(groups)
    groups_part1 =  groups[:int(num_groups*0.2)]
    groups_part2 =  groups[int(num_groups*0.2):int(num_groups*0.4)]
    groups_part3 =  groups[int(num_groups*0.4):int(num_groups*0.6)]
    groups_part4 =  groups[int(num_groups*0.6):int(num_groups*0.8)]
    groups_part5 =  groups[int(num_groups*0.8):]
    groups_train = np.concatenate((groups_part2, groups_part3, groups_part4, groups_part5))
    groups_test = groups_part1
    print(len(groups_train), len(groups_test))
    groups_n_train.append(groups_train)
    groups_n_test.append(groups_test)
    if i == 3:
        print(groups_part1, '\n\n', groups_part2, '\n\n', groups_part3, '\n\n', groups_part4, '\n\n', groups_part5, '\n\n')
        print(groups_train,'\n\n', groups_test)

68 16
28 7
17 4
13 3
[[110.  27.  15. 154. 197.]
 [  6.  36.  53. 114. 153.]
 [174. 146. 121.  18.  34.]] 

 [[ 68.  25. 175. 128. 152.]
 [165.  51. 129.   1. 122.]
 [ 60.  54.  83.  29. 216.]] 

 [[198. 201. 186. 168.  84.]
 [ 10. 139.  86. 131. 133.]
 [214.  28. 200.  69. 118.]] 

 [[ 75. 181. 217.  70.  85.]
 [185.   9.  67. 149. 162.]
 [144. 112. 184. 136. 206.]] 

 [[190.  21. 204.   5.  94.]
 [205.  76.  26.  42. 117.]
 [ 30.  92.  87. 159. 218.]
 [109.  65. 208. 145.  35.]] 


[[ 68.  25. 175. 128. 152.]
 [165.  51. 129.   1. 122.]
 [ 60.  54.  83.  29. 216.]
 [198. 201. 186. 168.  84.]
 [ 10. 139.  86. 131. 133.]
 [214.  28. 200.  69. 118.]
 [ 75. 181. 217.  70.  85.]
 [185.   9.  67. 149. 162.]
 [144. 112. 184. 136. 206.]
 [190.  21. 204.   5.  94.]
 [205.  76.  26.  42. 117.]
 [ 30.  92.  87. 159. 218.]
 [109.  65. 208. 145.  35.]] 

 [[110.  27.  15. 154. 197.]
 [  6.  36.  53. 114. 153.]
 [174. 146. 121.  18.  34.]]


In [68]:
for i in groups_n_train:
    print(len(i[0]))

2
3
4
5


In [69]:
svd['count'] = 1
svd

uid      tid    rating  count
0           0.0      0.0  2.493650      1
1           0.0      6.0  2.333071      1
2           0.0      8.0  2.713340      1
3           0.0      9.0  1.949588      1
4           0.0     12.0  2.477737      1
...         ...      ...       ...    ...
11741994  219.0  54964.0  1.816855      1
11741995  219.0  54965.0  2.315346      1
11741996  219.0  54966.0  1.954432      1
11741997  219.0  54967.0  2.071366      1
11741998  219.0  54968.0  2.377146      1

[11741999 rows x 4 columns]

In [70]:
pop_count = pop_count.sort_values(by=['count'],  ascending=False)
pop_count

tid  count  rating
166      166   1882  333.50
6310    6338   1589   92.25
17316  17377   1555   43.50
6254    6282   1396   17.50
13055  13104   1340   33.50
...      ...    ...     ...
25819  25941      1    0.25
43440  43743      1    0.25
54130  54607      1    0.25
27486  27620      1    0.25
25232  25344      1    0.25

[54480 rows x 3 columns]

In [71]:
# min_max
max_rating = pop_count.iloc[0]['count']
pop_normalized = pop_count.copy()
pop_normalized = pop_normalized[['tid', 'count']]
pop_normalized['rating'] = pop_normalized['count']
pop_normalized['rating'] /= max_rating
pop_normalized['rating'] *= 5
pop_normalized

tid  count    rating
166      166   1882  5.000000
6310    6338   1589  4.221573
17316  17377   1555  4.131243
6254    6282   1396  3.708820
13055  13104   1340  3.560043
...      ...    ...       ...
25819  25941      1  0.002657
43440  43743      1  0.002657
54130  54607      1  0.002657
27486  27620      1  0.002657
25232  25344      1  0.002657

[54480 rows x 3 columns]

In [72]:
def dcg_at_k(r, k, method=0):
    r = np.asfarray(r)[:k]
    for i in range(len(r)):
        r[i] = 2**r[i] -1
    
    if r.size:
        if method == 0:
            return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
        elif method == 1:
            return np.sum(r / np.log2(np.arange(2, r.size + 2)))
        else:
            raise ValueError('method must be 0 or 1.')
    return 0.


def ndcg_at_k(r, k, method=0):
    dcg_max = dcg_at_k(sorted(r, reverse=True), k, method)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k, method) / dcg_max

In [73]:
lambdas = []
for i in range(11):
    lambdas.append(i/10)
lambdas

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [74]:
top_n_size = 20
optimal_lambdas = []
results_precision = []
results_satisfaction = []
results_tau = []
results_DCG = []
results_nDCG = []
for i in range(len(groups_n_train)):
    results_tau.append([])
    results_nDCG.append([])
    results_precision.append([])
    results_DCG.append([])
    results_satisfaction.append([])
truth_rank = []
for i in range(top_n_size):
    truth_rank.append(i+1)

In [75]:
for lambda_ in tqdm(lambdas):
    top_n_lists_g = []
    for groups in groups_n_train:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    threshold = 0.0
    for i in range(len(groups_n_train)):
        groups = groups_n_train[i]
        top_n_lists = top_n_lists_g[i]

        precisions = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            high_rating = 0

            for k in range(top_n_size):
                for l in range(len(group)):
                    uid = group[l]
                    tid = top_n_list[k]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_rating += 1
                        break

            precision = high_rating / top_n_size
            precisions.append(precision)
        
        satisfactions = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            high_ratings_t = np.zeros(top_n_size)
            high_ratings_u = np.zeros(len(group))

            for k in range(top_n_size):
                for l in range(len(group)):
                    uid = group[l]
                    tid = top_n_list[k]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_ratings_t[k] += 1
                        high_ratings_u[l] += 1

            satisfaction_t = 0
            for k in range(top_n_size):
                satisfaction_t += math.log(high_ratings_t[k]+1, 10) / math.log(len(group)+1, 10)
            satisfaction_t /= top_n_size

            satisfaction_u = 0
            for k in range(len(group)):
                satisfaction_u += math.log(high_ratings_u[k]+1, 10) / math.log(top_n_size+1, 10)
            satisfaction_u /= len(group)

            satisfaction = 0.5*satisfaction_t + (1-0.5)*satisfaction_u
            satisfactions.append(satisfaction)
        
        taus = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            
            ground_truth = []
            for _, row in rating_table.iterrows():
                ground_truth.append(row[0])
            
            pred_rank = []
            for k in top_n_list:
                if k in ground_truth:
                    pred_rank.append(ground_truth.index(k)+1)
                else:
                    pred_rank.append(top_n_size+1)
            tau, p_value = kendalltau(truth_rank, pred_rank)
            taus.append(tau)

        nDCGs = []
        DCGs = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            
            truth_rating = []
            for k in top_n_list:
                r = rating_table[rating_table['tid']==k]
                if len(r) > 0:
                    truth_rating.append(r.iloc[0]['rating'])
                else:
                    truth_rating.append(0)
            nDCG = ndcg_at_k(truth_rating, top_n_size, method=1)
            DCG = dcg_at_k(truth_rating, top_n_size, method=1)
            nDCGs.append(nDCG)
            DCGs.append(DCG)
            

    
        avg_satisfaction = 0
        for satisfaction in satisfactions:
            avg_satisfaction += satisfaction
        avg_satisfaction /= len(satisfactions)
    
        avg_precision = 0
        for precision in precisions:
            avg_precision += precision
        avg_precision /= len(precisions)
        
        n_tau = 0
        avg_tau = 0
        for tau in taus:
            if not np.isnan(tau):
                avg_tau += tau
                n_tau += 1
        avg_tau /= n_tau
        
        avg_nDCG = 0
        for nDCG in nDCGs:
            avg_nDCG += nDCG
        avg_nDCG /= len(nDCGs)      
        
        avg_DCG = 0
        for DCG in DCGs:
            avg_DCG += DCG
        avg_DCG /= len(DCGs)
        
        results_precision[i].append(avg_precision)
        results_satisfaction[i].append(avg_satisfaction)
        results_tau[i].append(avg_tau)
        results_nDCG[i].append(avg_nDCG)
        results_DCG[i].append(avg_DCG)

In [76]:
ranks_precision = []
ranks_tau = []
ranks_DCG = []
ranks_nDCG = []
ranks_satisfaction = []

In [77]:
for i in results_precision:
    ranks_precision.append(rankdata(i))
for i in results_tau:
    ranks_tau.append(rankdata(i))
for i in results_DCG:
    ranks_DCG.append(rankdata(i))
for i in results_nDCG:
    ranks_nDCG.append(rankdata(i))
for i in results_satisfaction:
    ranks_satisfaction.append(rankdata(i))

In [78]:
for i in results_precision:
    print(i)
print()
for i in results_satisfaction:
    print(i)

[0.23897058823529413, 0.2375, 0.23970588235294119, 0.2551470588235294, 0.28088235294117647, 0.30882352941176466, 0.33970588235294114, 0.3632352941176471, 0.3507352941176469, 0.2963235294117647, 0.21250000000000002]
[0.2839285714285714, 0.2821428571428571, 0.27678571428571425, 0.28928571428571426, 0.30535714285714277, 0.3267857142857143, 0.34821428571428575, 0.3696428571428571, 0.3875, 0.3625, 0.26249999999999996]
[0.3411764705882353, 0.3382352941176471, 0.3352941176470588, 0.34117647058823525, 0.35, 0.4029411764705883, 0.42941176470588227, 0.45294117647058824, 0.4470588235294118, 0.4470588235294118, 0.34411764705882364]
[0.36538461538461536, 0.36538461538461536, 0.3538461538461538, 0.3576923076923077, 0.3692307692307692, 0.36538461538461536, 0.3923076923076923, 0.3923076923076923, 0.4230769230769231, 0.4, 0.27692307692307694]

[0.27041137846943686, 0.2691883712703287, 0.2709892932075776, 0.28317703573326414, 0.30243466553418136, 0.3209121978334245, 0.3385034097799742, 0.354006777592646

In [79]:
optimized_lambdas = []
for i in range(len(groups_n_test)):
    print(ranks_satisfaction[i])
#     print('--------------------------------------------------')
    print(ranks_precision[i])
#     print(ranks_tau[i])
#     print(ranks_DCG[i])
#     print(ranks_nDCG[i])
#     print(ranks_precision[i] + ranks_tau[i] + ranks_DCG[i] + ranks_nDCG[i])
#     ranks = (ranks_precision[i] + ranks_tau[i] + ranks_DCG[i] + ranks_nDCG[i]).tolist()
#     print(ranks.index(max(ranks)))
    print('--------------------------------------------------')
#     optimized_lambdas.append()

[ 3.  2.  4.  5.  7.  8.  9. 11. 10.  6.  1.]
[ 3.  2.  4.  5.  6.  8.  9. 11. 10.  7.  1.]
--------------------------------------------------
[ 4.  3.  2.  5.  6.  7.  9. 10. 11.  8.  1.]
[ 4.  3.  2.  5.  6.  7.  8. 10. 11.  9.  1.]
--------------------------------------------------
[ 4.  3.  2.  5.  6.  7. 10. 11.  9.  8.  1.]
[ 4.   2.   1.   3.   6.   7.   8.  11.   9.5  9.5  5. ]
--------------------------------------------------
[ 6.5  6.5  2.   4.   5.   3.   9.  10.  11.   8.   1. ]
[ 5.   5.   2.   3.   7.   5.   8.5  8.5 11.  10.   1. ]
--------------------------------------------------


In [80]:
final_results_precision = []
final_results_tau = []
final_results_DCG = []
final_results_nDCG = []
for i in range(len(groups_n_test)):
    final_results_tau.append([])
    final_results_nDCG.append([])
    final_results_precision.append([])
    final_results_DCG.append([])
truth_rank = []
for i in range(top_n_size):
    truth_rank.append(i+1)

In [81]:
print(lambdas)

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]


In [82]:
for lambda_ in tqdm(lambdas):
    top_n_lists_g = []
    for groups in groups_n_test:

        group_size = len(groups[0])
        top_n_lists = []

        for group in groups:
            rating_table = pd.DataFrame() 
            for member in group:
                prediction = svd[svd['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = prediction
                else:
                    rating_table = rating_table.set_index('tid').add(prediction.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= group_size 
            rating_table['rating'] *= lambda_
            pop = pop_normalized.copy()
            pop['rating'] *= (1 - lambda_)
            rating_table = rating_table.set_index('tid').add(pop.set_index('tid'), fill_value=0).reset_index()
    #         rating_table = rating_table[rating_table['count'] == group_size]
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            top_n_list = []
            for _, row in rating_table.iterrows():
                top_n_list.append(row[0])
            top_n_lists.append(top_n_list)
        top_n_lists_g.append(top_n_lists)   
        
    threshold = 0.0
    for i in range(len(groups_n_test)):
        groups = groups_n_test[i]
        top_n_lists = top_n_lists_g[i]

        precisions = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            high_rating = 0

            for k in range(top_n_size):
                for l in range(len(group)):
                    uid = group[l]
                    tid = top_n_list[k]
                    t = test[test['uid'] == uid]
                    t = t[t['tid'] == tid]
                    if len(t) > 0 and t.iloc[0]['rating'] > threshold:
                        high_rating += 1
                        break

            precision = high_rating / top_n_size
            precisions.append(precision)
        
        taus = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            rating_table = rating_table[:top_n_size]
            
            ground_truth = []
            for _, row in rating_table.iterrows():
                ground_truth.append(row[0])
            
            pred_rank = []
            for k in top_n_list:
                if k in ground_truth:
                    pred_rank.append(ground_truth.index(k)+1)
                else:
                    pred_rank.append(top_n_size+1)
            tau, p_value = kendalltau(truth_rank, pred_rank)
            taus.append(tau)

        nDCGs = []
        DCGs = []
        for j in (range(len(groups))):

            group = groups[j]
            top_n_list = top_n_lists[j]

            rating_table = pd.DataFrame() 
            for member in group:
                average = test[test['uid'] == member].copy()
                if len(rating_table) == 0:
                    rating_table = average
                else:
                    rating_table = rating_table.set_index('tid').add(average.set_index('tid'), fill_value=0).reset_index()
            rating_table['rating'] /= len(group) 
            rating_table = rating_table.sort_values(by=['rating'],  ascending=False)
            
            truth_rating = []
            for k in top_n_list:
                r = rating_table[rating_table['tid']==k]
                if len(r) > 0:
                    truth_rating.append(r.iloc[0]['rating'])
                else:
                    truth_rating.append(0)
            nDCG = ndcg_at_k(truth_rating, top_n_size, method=1)
            DCG = dcg_at_k(truth_rating, top_n_size, method=1)
            nDCGs.append(nDCG)
            DCGs.append(DCG)
    
        avg_precision = 0
        for precision in precisions:
            avg_precision += precision
        avg_precision /= len(precisions)
        
        n_tau = 0
        avg_tau = 0
        for tau in taus:
            if not np.isnan(tau):
                avg_tau += tau
                n_tau += 1
        if n_tau != 0:
            avg_tau /= n_tau
        else:
            avg_tau = -200 #NA
        
        avg_nDCG = 0
        for nDCG in nDCGs:
            avg_nDCG += nDCG
        avg_nDCG /= len(nDCGs)      
        
        avg_DCG = 0
        for DCG in DCGs:
            avg_DCG += DCG
        avg_DCG /= len(DCGs)
        
        final_results_precision[i].append(avg_precision)
        final_results_tau[i].append(avg_tau)
        final_results_nDCG[i].append(avg_nDCG)
        final_results_DCG[i].append(avg_DCG)

In [83]:
for i in final_results_precision:
    print(i)
print()
for i in final_results_tau:
    print(i)
print()
for i in final_results_DCG:
    print(i)    
print()
for i in final_results_nDCG:
    print(i)

[0.35000000000000003, 0.353125, 0.375, 0.4156250000000001, 0.4750000000000001, 0.503125, 0.5625, 0.590625, 0.590625, 0.525, 0.459375]
[0.36428571428571427, 0.36428571428571427, 0.3714285714285714, 0.3785714285714285, 0.40714285714285714, 0.4428571428571428, 0.4785714285714286, 0.5428571428571429, 0.5357142857142858, 0.5857142857142856, 0.5214285714285715]
[0.4125, 0.4125, 0.4125, 0.4125, 0.4625, 0.5125000000000001, 0.525, 0.5874999999999999, 0.575, 0.575, 0.4625]
[0.28333333333333327, 0.28333333333333327, 0.28333333333333327, 0.28333333333333327, 0.28333333333333327, 0.3, 0.3333333333333333, 0.45, 0.4666666666666666, 0.4166666666666667, 0.3]

[-0.15838334242861501, -0.15366653187936724, -0.139381370521526, -0.1442397108011675, -0.17788106334383075, -0.07937697751135132, -0.04516897944478169, -0.023260115552222557, 0.05129106026639394, -0.0147827290567624, 0.02634664715115671]
[-0.1079069236705317, -0.08316394127828655, -0.002291040419574862, 0.006030742896657719, -0.022606944674073853,