In [15]:
from scipy import mat, dot
import numpy as np
import scipy as sp
from numpy.random import random
import os
import numpy as np
import pandas as pd
import tqdm
import time
import math

dir_ = './data/'
file_name = 'normalized_filter_track_5_user_100.csv'

In [84]:
print(U, '\n\n', s, '\n\n', V)

[[-0.56033527 -0.25238511 -0.78316411 -0.09476346]
 [-0.56352336 -0.26200036  0.55458092 -0.55338706]
 [-0.43036455 -0.22694435  0.28095316  0.82725325]
 [-0.42807962  0.90341232  0.01262122  0.02084979]] 

 [11.70432354  5.05989766  1.48661359  0.44297423] 

 [[-0.32723506 -0.36353716 -0.57884106 -0.65245764]
 [ 0.51588378  0.69632766 -0.41252766 -0.28073591]
 [ 0.44223716 -0.44913355 -0.56639882  0.53094041]
 [-0.65666387  0.42573181 -0.41708073  0.46215652]]


In [122]:
def euclidean_distance(u1, u2):

        sum_ = 0.0
        for i in range(num_tracks):
            q = vt[i,u1]
            p = vt[i,u2]
            sum_ += pow((q-p), 2)

        result = math.sqrt(sum_)

        return result

In [123]:
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import svds
B = [[1,1,4,5],
     [1,0,5,4],
     [5,4,0,1],
     [4,5,1,1]]
C = mat(B, dtype=float)
u, s, vt = svds(C, k=2) # k is the number of factors
s

array([ 7.53616365, 10.52288898])

In [126]:
np.set_printoptions(suppress=True)
print(u, '\n\n', s, '\n\n', vt)

[[ 0.45891681 -0.52425604]
 [ 0.53993591 -0.473926  ]
 [-0.52955415 -0.47928741]
 [-0.46630139 -0.5204165 ]] 

 [ 7.53616365 10.52288898] 

 [[-0.46630139 -0.52955415  0.53993591  0.45891681]
 [-0.5204165  -0.47928741 -0.473926   -0.52425604]]


In [125]:
num_tracks =2
for i in range(4):
    for j in range(i,4):
        if not i==j:
            print(i, j, euclidean_distance(i,j))

0 1 0.07544875171742622
0 2 1.0073107109411819
0 3 0.9252261577588552
1 2 1.0695034972656152
1 3 0.9894933042359043
2 3 0.09537929011458667
